language: scala

sudo: false

cache:
  # these directories are cached to S3 at the end of the build
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache

matrix:
  include:
    - name: Spark 2.4.6
      env: SPARK_VERSION=2.4.6
      scala:
        - 2.11.12
      jdk:
        - openjdk8
    - name: Spark 3.0.0 (Java 8)
      env: SPARK_VERSION=3.0.0
      scala:
        - 2.12.11
      jdk:
        - openjdk8
    - name: Spark 3.0.0 (Java 11)
      env: SPARK_VERSION=3.0.0
      scala:
        - 2.12.11
      jdk:
        - openjdk11

script:
  - sbt -jvm-opts travis/jvmopts.test    ++$TRAVIS_SCALA_VERSION -Dspark.version=$SPARK_VERSION scalastyle
  - sbt -jvm-opts travis/jvmopts.test    ++$TRAVIS_SCALA_VERSION -Dspark.version=$SPARK_VERSION test
  - sbt -jvm-opts travis/jvmopts.compile ++$TRAVIS_SCALA_VERSION -Dspark.version=$SPARK_VERSION assembly

before_cache:
  # cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt  -name "*.lock"               -print -delete
